project_id = "oscgxbtukrppycrchvdl"

[functions.create-stripe-checkout]
verify_jwt = true

[functions.generate-payment-link]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.translate]
verify_jwt = true

[functions.send-sms]
verify_jwt = false

[functions.generate-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.send-admin-email]
verify_jwt = false

[functions.send-verification-email]
verify_jwt = false

[functions.verify-email-token]
verify_jwt = false